steps:
- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    cd javascript
    npm install

- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    cd javascript
    npm test

- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    cd javascript
    npm run
- name: maven:latest
  entrypoint: mvn
  args: ["clean", "install", "-DskipTests"]
- name: maven:latest
  entrypoint: mvn
  args: ["test"]


