 

image: maven:latest
variables:
MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
MAVEN_CLI_OPTS: "--batch-mode"
cache:
paths:
 - .m2/repository
 - javascript/node_modules
stages: 
 - build
 - test
 - deploy
 - server
java: 
stage: build
script: 
 - mvn $MAVEN_CLI_OPTS compile
 - mvn clean install
artifacts:
expire_in: 5 days
paths:
 - "target/"
node: 
image: node:latest
stage: build
before_script:
 - cd javascript
 - yarn install
script: 
 - npm run
test: 
stage: test
script: 
 - mvn $MAVEN_CLI_OPTS test
deploy_image:
image: docker:latest
stage: deploy
services:
 - docker:dind
before_script:
 - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
script:
 - docker build -t "nolan45/ping-gitlab:latest" .
 - docker push "nolan45/ping-gitlab:latest"
 - if [[ $CI_COMMIT_BRANCH == "main" ]] ; then docker run -d "nolan45/ping-gitlab" ; fi
Connection: 
stage: server
image: ubuntu:latest
before_script:
 - apt-get update -qq
 - apt-get install -qq git
 - 'which ssh-agent || ( apt-get install -qq openssh-client )'
 - eval $(ssh-agent -s)
 - ssh-add <(echo "$$SSH_PRIVATE_KEY")
 - mkdir -p ~/.ssh
 - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
script: 
 - ssh nolan@34.69.13.25 " sudo docker pull nolan45/ping-gitlab:latest && sudo docker run -d -p 8080:8080 nolan45/ping-gitlab:latest"

