steps:
- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    cd javascript
    npm install

- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    cd javascript
    npm test

- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    cd javascript
    npm run
- name: maven:latest
  entrypoint: mvn
  args: ["clean", "install", "-DskipTests"]
- name: maven:latest
  entrypoint: mvn
  args: ["test"]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$docker-username --password=$$docker-password']
  secretEnv: ['docker-username', 'docker-password']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/nolan45/ping-gitlab', '-f', './Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$docker-username --password=$$docker-password']
  secretEnv: ['docker-username', 'docker-password']


