steps:
- name: node
  entrypoint: bash
  args: 
  - '-c'
  - |
    ls
    cd javascript
    npm install

- name: node
  entrypoint: npm
  args: 
  - '-c'
  - |
    cd javascript
    npm test
- name: node
  entrypoint: npm
    - '-c'
    - |
    cd javascript
    npm run build
- name: maven:latest
  entrypoint: mvn
  args: ["clean", "install", "-DskipTests"]
- name: maven:latest
  entrypoint: mvn
  args: ["test"]


